{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kagesec.serviceAccountName" . }}
  labels:
    {{- include "kagesec.labels" . | nindent 4 }}
{{- end }}
