"""
GitHub Issues Exporter — Gap 21

Creates GitHub Issues for each finding via the GitHub REST API v3.

Usage:
  kagesec export --format github report.json \
    --github-repo owner/repo \
    --github-token ghp_xxx
"""
from __future__ import annotations

import httpx
from typing import List
from scanner.core.scan_result import ScanResult, Finding, Severity

_SEVERITY_LABEL = {
    Severity.CRITICAL: "severity: critical",
    Severity.HIGH: "severity: high",
    Severity.MEDIUM: "severity: medium",
    Severity.LOW: "severity: low",
    Severity.INFO: "severity: info",
}


def export_to_github(
    result: ScanResult,
    repo: str,
    token: str,
    dry_run: bool = False,
) -> List[dict]:
    """
    Create GitHub Issues for each finding.

    *repo*  — 'owner/repo' format (e.g. 'acme/myapp')
    *token* — GitHub Personal Access Token with 'repo' scope
    Returns list of created issue dicts.
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    client = httpx.Client(headers=headers, timeout=20)
    api_base = f"https://api.github.com/repos/{repo}"
    created = []

    # Ensure labels exist
    _ensure_labels(client, api_base)

    for f in result.findings:
        if f.false_positive_suppressed:
            continue

        title, body = _build_issue(f)
        labels = ["KageSec Security Finding", _SEVERITY_LABEL.get(f.severity, "severity: info")]

        if dry_run:
            created.append({"dry_run": True, "title": title})
            continue

        try:
            resp = client.post(
                f"{api_base}/issues",
                json={"title": title, "body": body, "labels": labels},
            )
            resp.raise_for_status()
            data = resp.json()
            created.append({
                "number": data.get("number"),
                "url": data.get("html_url", ""),
                "title": title,
            })
        except Exception as e:
            created.append({"error": str(e), "title": title})

    client.close()
    return created


def _build_issue(f: Finding) -> tuple:
    title = f"{f.severity.upper()} — {f.title}"
    if len(title) > 256:
        title = title[:253] + "..."

    lines = [
        f"## {f.severity.upper()} Security Finding",
        "",
        f"**Title:** {f.title}",
        f"**URL:** `{f.url}`",
        f"**Parameter:** `{f.parameter or 'N/A'}`",
        f"**CVSS:** {f.cvss or 'N/A'}",
        f"**CWE:** {f.cwe or 'N/A'}",
        f"**OWASP:** {f.owasp_category or 'N/A'}",
        f"**Confidence:** {f.confidence:.0%}",
        "",
        "### Evidence",
        f.evidence,
        "",
        "### Description",
        f.description,
        "",
        "### Remediation",
        f.remediation,
    ]
    if f.poc_curl:
        lines += ["", "### PoC (curl)", f"```bash\n{f.poc_curl}\n```"]

    lines += [
        "",
        "---",
        "*Generated by [KageSec](https://github.com/kagesec/kagesec) security scanner.*",
    ]
    return title, "\n".join(lines)


def _ensure_labels(client: httpx.Client, api_base: str):
    """Create KageSec severity labels if they don't exist."""
    label_configs = [
        ("KageSec Security Finding", "e11d48", "Finding from KageSec security scan"),
        ("severity: critical", "b60205", "Critical severity finding"),
        ("severity: high", "d93f0b", "High severity finding"),
        ("severity: medium", "fbca04", "Medium severity finding"),
        ("severity: low", "0075ca", "Low severity finding"),
        ("severity: info", "cfd3d7", "Informational finding"),
    ]
    try:
        existing_resp = client.get(f"{api_base}/labels?per_page=100")
        existing_names = {item["name"] for item in existing_resp.json() if isinstance(item, dict)}
        for name, color, desc in label_configs:
            if name not in existing_names:
                client.post(f"{api_base}/labels", json={"name": name, "color": color, "description": desc})
    except Exception:
        pass
